---
title: "Data Science Lab"
author: "Lorenzo Mauri"
date: "17 aprile 2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(magrittr) #package for concatenating commands %>%
library(tibble)  #set data as tibble object
library(dplyr)  # data management (filter,select,summarize,ecc...)
library(lubridate) #manipulating dates
library(tidyr)
library(pander)
knitr::opts_chunk$set(echo = TRUE)
```



```{r,warning=F}

file_path = "C:\\Users\\loren\\Desktop\\GITHUB REPO\\Covid19_prediction\\data\\comune_giorno.csv"
data=read.csv(file_path)

```

```{r}
#reshaping dataset
data=gather(data,'MASCHI_15','MASCHI_16','MASCHI_17','MASCHI_18','MASCHI_19','MASCHI_20','FEMMINE_15','FEMMINE_16','FEMMINE_17','FEMMINE_18','FEMMINE_19','FEMMINE_20',key='GENERE/ANNO',value='MORTI')

#elimino le righe con 0 morti e le colonne dei totali 
data=data%>%subset(MORTI>0)
data = data[,-c(10:15)]


```
```{r}
attach(data)
```

```{r}
data=data%>%separate(`GENERE/ANNO`,into=c('GENERE','ANNO'),sep='_')
attach(data)

data$DATA=ifelse(GE%>%nchar() <=3,paste('0',GE,ANNO,sep=''),paste(GE,ANNO,sep=''))%>%mdy()

mdy()
data$DATA=ifelse(GE%>%nchar() <=3,paste('0',GE,ANNO,sep=''),paste(GE,ANNO,sep=''))%>%mdy()

data=data[,-9]

data=data%>%select('DATA','NOME_REGIONE','NOME_PROVINCIA','NOME_COMUNE','GENERE','MORTI','CL_ETA','DATA_INIZIO_DIFF','COD_PROVCOM','PROV','REG')%>%View()
```

